# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui' close
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtGui
from PyQt5 import QtWidgets, QtCore


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(380, 515)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(380, 515))
        MainWindow.setMaximumSize(QtCore.QSize(380, 515))
        icon = QtGui.QIcon()
        # icon.addPixmap(QtGui.QPixmap(""), QtGui.QIcon.Normal, QtGui.QIcon.Off) # ../../Pictures/icons/password_page_icon-removebg-preview.png
        icon.addPixmap(QtGui.QPixmap("main window icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        MainWindow.setWindowIcon(icon) # ../../Pictures/icons/password_page_icon-removebg-preview.png
        MainWindow.setAutoFillBackground(False)
#         MainWindow.setStyleSheet("background-color: rgb(0, 0, 89; border-radius: 20px);\n"
# "border-radius: 50px;")
        self.main_frame = QtWidgets.QWidget(MainWindow)
        self.main_frame.setMaximumSize(QtCore.QSize(380, 515))
        self.main_frame.setMinimumSize(QtCore.QSize(380, 515))
        self.main_frame.setObjectName("main_frame")
        self.main_frame.setStyleSheet("border-radius: 20px")
        self.main_frame.setStyleSheet("background-color: rgb(0, 0, 89; border-radius: 20px);\n"
                                 "border-radius: 20px;")
        self.login_container = QtWidgets.QFrame(self.main_frame)
        self.login_container.setGeometry(QtCore.QRect(10, 40, 361, 451))
        self.login_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.login_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.login_container.setObjectName("login_container")
        self.picture_frame = QtWidgets.QFrame(self.login_container)
        self.picture_frame.setGeometry(QtCore.QRect(10, 10, 341, 261))
        self.picture_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.picture_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.picture_frame.setObjectName("picture_frame")
        self.picture_label = QtWidgets.QLabel(self.picture_frame)
        self.picture_label.setGeometry(QtCore.QRect(10, 10, 321, 241))
        self.picture_label.setText("")
        self.picture_label.setPixmap(QtGui.QPixmap("login background photo.png")) # ../../Pictures/icons/login photo 2.png
        self.picture_label.setScaledContents(True)
        self.picture_label.setObjectName("picture_label")
        self.boxes_frame = QtWidgets.QFrame(self.login_container)
        self.boxes_frame.setGeometry(QtCore.QRect(10, 280, 341, 171))
        font = QtGui.QFont()
        font.setFamily("Fixedsys")
        font.setBold(False)
        font.setWeight(50)
        self.boxes_frame.setFont(font)

        self.boxes_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.boxes_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.boxes_frame.setObjectName("boxes_frame")
        self.login_button = QtWidgets.QPushButton(self.boxes_frame)
        self.login_button.setEnabled(True)
        self.login_button.setGeometry(QtCore.QRect(80, 110, 61, 61))
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setMouseTracking(False)
        self.login_button.setTabletTracking(True)
        self.login_button.setAcceptDrops(False)
        self.login_button.setAutoFillBackground(False)
        self.login_button.setStyleSheet("\n"
"border_radius: 100px;            \n"
"\n"
"color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.login_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("login icon blue.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_button.setIcon(icon1) # ../../Pictures/icons/login_button_icon3-removebg-preview.png
        self.login_button.setIconSize(QtCore.QSize(69, 79))
        self.login_button.setAutoDefault(False)
        self.login_button.setDefault(False)
        self.login_button.setFlat(False)
        self.login_button.setObjectName("login_button")
        self.username_line = QtWidgets.QLineEdit(self.boxes_frame)
        self.username_line.setGeometry(QtCore.QRect(30, 20, 211, 20))
        self.username_line.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-radius: 10px;")
        self.username_line.setObjectName("username_line")
        self.password_line = QtWidgets.QLineEdit(self.boxes_frame)
        self.password_line.setGeometry(QtCore.QRect(30, 70, 211, 20))
        self.password_line.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"border-radius: 10px;") # background-color: rgb(7, 94, 255);
        self.password_line.setObjectName("password_line")
        self.password_line.setEchoMode(QLineEdit.Password)
        self.username_label = QtWidgets.QLabel(self.boxes_frame)
        self.username_label.setGeometry(QtCore.QRect(250, 20, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.username_label.setStyleSheet("color: rgb(12, 255, 12);")
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.boxes_frame)
        self.password_label.setGeometry(QtCore.QRect(250, 70, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setStyleSheet("color: rgb(12, 255, 12);")
        self.password_label.setObjectName("password_label")
        self.frame = QtWidgets.QFrame(self.main_frame)
        self.frame.setGeometry(QtCore.QRect(290, 10, 81, 31))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.window_maxsimize = QtWidgets.QPushButton(self.frame)
        self.window_maxsimize.setGeometry(QtCore.QRect(0, 0, 21, 21))
        self.window_maxsimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.window_maxsimize.setStyleSheet("background-color: rgb(0, 255, 0);\n"
"border-radius: 10px;")
        self.window_maxsimize.setText("")
        self.window_maxsimize.setObjectName("window_maxsimize")
        self.window_minimize = QtWidgets.QPushButton(self.frame)
        self.window_minimize.setGeometry(QtCore.QRect(30, 0, 21, 21))
        self.window_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.window_minimize.setStyleSheet("background-color: rgb(255, 255, 0);\n"
"border-radius: 10px;")
        self.window_minimize.setText("")
        self.window_minimize.setObjectName("window_minimize")
        self.window_closer = QtWidgets.QPushButton(self.frame)
        self.window_closer.setGeometry(QtCore.QRect(60, 0, 21, 21))
        self.window_closer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.window_closer.setStyleSheet("background-color: rgb(255, 0, 4);\n"
"border-radius: 10px;")
        self.window_closer.setText("")
        self.window_closer.setObjectName("window_closer")
        MainWindow.setCentralWidget(self.main_frame)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.window_maxsimize.clicked.connect(MainWindow.showMaximized)
        self.window_minimize.clicked.connect(MainWindow.showMinimized)
        self.window_closer.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Password Generator Login", "Password Generator Login"))
        self.username_label.setText(_translate("MainWindow", "نام کاربری:"))
        self.password_label.setText(_translate("MainWindow", "رمز عبور:"))



# class RootMain(QMainWindow):
#     def __init__(self):
#         QMainWindow.__init__(self)
#
#         self.ui = Ui_MainWindow()
#
#         self.ui.setupUi(self)
#
#         self.setWindowFlag(Qt.FramelessWindowHint)
#         self.setAttribute(Qt.WA_TranslucentBackground)
#
#         self.show()
#         # self.oldPos = ""
#
#     def mousePressEvent(self, evt: QtGui.QMouseEvent) -> None:
#         # print("come")
#         self.oldPos = evt.globalPos()
#         # self.mouseMoveEvent(self.oldPos)
#
#     def mouseMoveEvent(self, evt: QtGui.QMouseEvent) -> None:
#         # print("move")
#         delta = QPoint(evt.globalPos() - self.oldPos)
#
#         self.move(self.x() + delta.x(), self.y() + delta.y())
#
#         self.oldPos = evt.globalPos()
#
#
# if __name__ == "__main__":
#     import sys
#
#     app = QApplication(sys.argv)
#
#     root = RootMain()
#
#     sys.exit(app.exec_())


