# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progressBar.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingWindow(object):
    def setupUi(self, LoadingWindow):
        LoadingWindow.setObjectName("LoadingWindow")
        LoadingWindow.resize(345, 215)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(LoadingWindow.sizePolicy().hasHeightForWidth())
        LoadingWindow.setSizePolicy(sizePolicy)
        LoadingWindow.setMinimumSize(QtCore.QSize(345, 215))
        LoadingWindow.setMaximumSize(QtCore.QSize(345, 215))
        LoadingWindow.setStyleSheet("color: rgb(12, 255, 12);")
        self.loadingShow = QtWidgets.QWidget(LoadingWindow)
        self.loadingShow.setObjectName("loadingShow")
        self.container = QtWidgets.QFrame(self.loadingShow)
        self.container.setGeometry(QtCore.QRect(10, 10, 321, 171))
        self.container.setStyleSheet("background-color: rgb(0, 0, 89);\n"
"border-radius: 20px;")
        self.container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.container.setObjectName("container")
        self.textLabel = QtWidgets.QLabel(self.container)
        self.textLabel.setGeometry(QtCore.QRect(60, 40, 201, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.textLabel.setFont(font)
        self.textLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.textLabel.setObjectName("textLabel")
        self.progressBar = QtWidgets.QProgressBar(self.container)
        self.progressBar.setGeometry(QtCore.QRect(20, 110, 281, 41))
        self.progressBar.setCursor(QtGui.QCursor(QtCore.Qt.WaitCursor))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("QProgressBar::chunk {\n"
"    color: rgb(255, 0, 255);\n"
"    text-align: center;\n"
"    border-radius: 15px;\n"
"    background-color: #009688;\n"
"    border-style: none;    \n"
"}\n"
"\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName("progressBar")
        self.window_closer = QtWidgets.QPushButton(self.container)
        self.window_closer.setGeometry(QtCore.QRect(290, 10, 21, 23))
        self.window_closer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.window_closer.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 0, 0);")
        self.window_closer.setText("")
        self.window_closer.setObjectName("window_closer")
        self.window_minimize = QtWidgets.QPushButton(self.container)
        self.window_minimize.setGeometry(QtCore.QRect(260, 10, 21, 23))
        self.window_minimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.window_minimize.setStyleSheet("border-radius: 10px;\n"
"background-color: yellow;")
        self.window_minimize.setText("")
        self.window_minimize.setObjectName("window_minimize")
        self.window_masimize = QtWidgets.QPushButton(self.container)
        self.window_masimize.setGeometry(QtCore.QRect(230, 10, 21, 23))
        self.window_masimize.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.window_masimize.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(0, 255, 0);\n"
"/*background-color: lightgreen;")
        self.window_masimize.setText("")
        self.window_masimize.setObjectName("window_masimize")
        LoadingWindow.setCentralWidget(self.loadingShow)
        self.statusbar = QtWidgets.QStatusBar(LoadingWindow)
        self.statusbar.setObjectName("statusbar")
        LoadingWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoadingWindow)
        self.window_closer.clicked.connect(LoadingWindow.close)
        self.window_minimize.clicked.connect(LoadingWindow.showMinimized)
        self.window_masimize.clicked.connect(LoadingWindow.showFullScreen)
        QtCore.QMetaObject.connectSlotsByName(LoadingWindow)

    def retranslateUi(self, LoadingWindow):
        _translate = QtCore.QCoreApplication.translate
        LoadingWindow.setWindowTitle(_translate("LoadingWindow", "MainWindow"))
        self.textLabel.setText(_translate("LoadingWindow", "در حال اجرای درخواست..."))



from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
from PyQt5 import QtGui
from PyQt5 import QtWidgets, QtCore

# from progectFile import progectClass
from login import Ui_MainWindow

class RootMain(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)

        self.ui = Ui_LoadingWindow()

        self.ui.setupUi(self)

        self.setWindowFlag(Qt.FramelessWindowHint)
        self.setAttribute(Qt.WA_TranslucentBackground)

        self.show()
        # self.oldPos = ""

    def mousePressEvent(self, evt: QtGui.QMouseEvent) -> None:
        # print("come")
        self.oldPos = evt.globalPos()
        # self.mouseMoveEvent(self.oldPos)

    def mouseMoveEvent(self, evt: QtGui.QMouseEvent) -> None:
        # print("move")
        delta = QPoint(evt.globalPos() - self.oldPos)

        self.move(self.x() + delta.x(), self.y() + delta.y())

        self.oldPos = evt.globalPos()

#
if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)

    root = RootMain()

    sys.exit(app.exec_())
