# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_main(object):
    def setupUi(self, main):
        main.setObjectName("main")
        main.resize(580, 470)
        main.setMinimumSize(QtCore.QSize(580, 470))
        main.setMaximumSize(QtCore.QSize(580, 470))
        self.pageFrame = QtWidgets.QWidget(main)
        self.pageFrame.setStyleSheet("")
        self.pageFrame.setObjectName("pageFrame")
        self.show_data_frame = QtWidgets.QFrame(self.pageFrame)
        self.show_data_frame.setGeometry(QtCore.QRect(70, 30, 471, 361))
        self.show_data_frame.setStyleSheet("border-radius: 0;\n"
"background-color: rgb(0, 0, 89);")
        self.show_data_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.show_data_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.show_data_frame.setObjectName("show_data_frame")
        self.scrollArea = QtWidgets.QScrollArea(self.show_data_frame)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 241, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 241, 361))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.show_data_textEdit = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.show_data_textEdit.setGeometry(QtCore.QRect(0, 0, 241, 361))
        self.show_data_textEdit.setStyleSheet("font: 87 8pt \"Arial Black\";\n"
"font: 87 10pt \"Arial Black\";\n"
"font: 87 12pt \"Arial Black\";\n"
"border-radius: 10px;\n"
"color: rgb(12, 255, 12);\n"
"background-color: rgb(0, 0, 89);")
        self.show_data_textEdit.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.show_data_textEdit.setOverwriteMode(False)
        self.show_data_textEdit.setObjectName("show_data_textEdit")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.show_data_image = QtWidgets.QLabel(self.show_data_frame)
        self.show_data_image.setGeometry(QtCore.QRect(280, 20, 171, 211))
        self.show_data_image.setText("")
        self.show_data_image.setPixmap(QtGui.QPixmap("../../Pictures/icons/show from database.png"))
        self.show_data_image.setScaledContents(True)
        self.show_data_image.setObjectName("show_data_image")
        main.setCentralWidget(self.pageFrame)
        self.statusbar = QtWidgets.QStatusBar(main)
        self.statusbar.setObjectName("statusbar")
        main.setStatusBar(self.statusbar)

        self.retranslateUi2(main)
        QtCore.QMetaObject.connectSlotsByName(main)

    def retranslateUi2(self, main):
        _translate = QtCore.QCoreApplication.translate
        main.setWindowTitle(_translate("main", "MainWindow"))
        self.show_data_textEdit.setHtml(_translate("main", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial Black\'; font-size:12pt; font-weight:80; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.show_data_textEdit.setPlaceholderText(_translate("main", "اطلاعاتی جهت چاپ یا نمایش موجود نمی باشد"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main = QtWidgets.QMainWindow()
    ui = Ui_main()
    ui.setupUi(main)
    main.show()
    sys.exit(app.exec_())
